{
	'targets': 
	[
		{
			'target_name': "node-box2d",
			'variables': {
				'BOX2D_PATH': "box2d/Box2D"
			},
			'include_dirs':
			[
				"<(module_root_dir)",
				"<(module_root_dir)/<(BOX2D_PATH)",
				"<!(node -e \"require('nan')\")"
			],
			'sources':
			[
				"node-box2d.cc",
				"<(BOX2D_PATH)/Box2D/Collision/b2BroadPhase.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/b2CollideCircle.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/b2CollideEdge.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/b2CollidePolygon.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/b2Collision.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/b2Distance.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/b2DynamicTree.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/b2TimeOfImpact.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/Shapes/b2ChainShape.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/Shapes/b2CircleShape.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/Shapes/b2EdgeShape.cpp",
				"<(BOX2D_PATH)/Box2D/Collision/Shapes/b2PolygonShape.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2BlockAllocator.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2Draw.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2FreeList.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2Math.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2Settings.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2StackAllocator.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2Stat.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2Timer.cpp",
				"<(BOX2D_PATH)/Box2D/Common/b2TrackedBlock.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/b2Body.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/b2ContactManager.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/b2Fixture.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/b2Island.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/b2World.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/b2WorldCallbacks.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2ChainAndCircleContact.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2ChainAndPolygonContact.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2CircleContact.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2Contact.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2ContactSolver.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2EdgeAndCircleContact.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2EdgeAndPolygonContact.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2PolygonAndCircleContact.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Contacts/b2PolygonContact.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2DistanceJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2FrictionJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2GearJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2Joint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2MotorJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2MouseJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2PrismaticJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2PulleyJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2RevoluteJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2RopeJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2WeldJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Dynamics/Joints/b2WheelJoint.cpp",
				"<(BOX2D_PATH)/Box2D/Particle/b2Particle.cpp",
				"<(BOX2D_PATH)/Box2D/Particle/b2ParticleAssembly.cpp",
				"<(BOX2D_PATH)/Box2D/Particle/b2ParticleGroup.cpp",
				"<(BOX2D_PATH)/Box2D/Particle/b2ParticleSystem.cpp",
				"<(BOX2D_PATH)/Box2D/Particle/b2VoronoiDiagram.cpp",
				"<(BOX2D_PATH)/Box2D/Rope/b2Rope.cpp"
			]
		}
	]
}
